name: "ga4_funnel_project"
version: "1.0.0"
profile: "ga4_funnel_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ga4_funnel_project:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table

    staging.ga4:
      +tags: ["staging", "ga4"]

    intermediate.ga4:
      +tags: ["intermediate", "ga4"]

    marts.ga4:
      +tags: ["mart", "ga4"]
