version: 2

models:
  - name: int_ga4__sessionized_events
    description: Adds session_id to each flattened GA4 event.
    columns:
      - name: session_id
        description: Unique identifier for a user session (user + timestamp).
        tests:
          - not_null
      - name: user_pseudo_id
        tests:
          - not_null
      - name: event_timestamp
        tests:
          - not_null

  - name: int_ga4__user_sessions
    description: Aggregates events into session-level rows with duration and engagement metrics.
    columns:
      - name: session_id
        tests:
          - not_null
      - name: user_pseudo_id
        tests:
          - not_null
      - name: session_start
        tests:
          - not_null
      - name: session_end
        tests:
          - not_null

  - name: int_ga4__ecommerce_events
    description: Filters and standardizes ecommerce events like view_item, add_to_cart, and purchase.
    columns:
      - name: event_name
        tests:
          - not_null
          - accepted_values:
              values: ["view_item", "add_to_cart", "purchase"]
      - name: item_name
      - name: quantity
